/**
 * Guards the design system's contract with the components that consume it.
 *
 * Both failures this catches shipped unnoticed in the previous UI: `--radius-xs`
 * and `.spin` were referenced by components but never defined, so corners fell
 * back to square and every "loading" spinner sat perfectly still. Neither breaks
 * a build or a render test — only a stylesheet cross-check finds them.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const srcDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const css = fs.readFileSync(path.join(srcDir, 'index.css'), 'utf8');

/** Declarations only — comments describe what the system no longer does. */
const cssDeclarations = css.replace(/\/\*[\s\S]*?\*\//g, '');

/** Every .jsx file under src/, excluding tests. */
function componentFiles(dir = srcDir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name !== 'tests') componentFiles(full, acc);
    } else if (entry.name.endsWith('.jsx')) {
      acc.push(full);
    }
  }
  return acc;
}

const sources = componentFiles().map((file) => ({
  name: path.relative(srcDir, file),
  text: fs.readFileSync(file, 'utf8'),
}));

/** Custom properties the stylesheet declares. */
const definedTokens = new Set(
  [...css.matchAll(/^\s*(--[\w-]+)\s*:/gm)].map((m) => m[1])
);

/** Class selectors the stylesheet declares. */
const definedClasses = new Set(
  [...css.matchAll(/\.([a-zA-Z][\w-]*)/g)].map((m) => m[1])
);

describe('Every token referenced by a component is defined', () => {
  it.each(sources)('$name', ({ text }) => {
    const referenced = [...text.matchAll(/var\((--[\w-]+)/g)].map((m) => m[1]);
    const missing = [...new Set(referenced)].filter((t) => !definedTokens.has(t));

    expect(missing).toEqual([]);
  });
});

describe('Every shared class name used by a component is defined', () => {
  // Classes generated by the libraries we render, not by our stylesheet
  const EXTERNAL = new Set(['form-control', 'MuiBox-root']);

  it.each(sources)('$name', ({ text }) => {
    const used = [];
    // Static className="a b c"
    for (const [, value] of text.matchAll(/className="([^"{}]+)"/g)) {
      used.push(...value.split(/\s+/).filter(Boolean));
    }
    // Template-literal className={`a ${x ? 'b' : ''}`} — collect the literal parts
    for (const [, value] of text.matchAll(/className=\{`([^`]+)`\}/g)) {
      for (const chunk of value.split(/\$\{[^}]*\}/)) {
        used.push(...chunk.split(/\s+/).filter(Boolean));
      }
    }
    // Ternary results inside those expressions, e.g. `${active ? ' nav-link-active' : ''}`.
    // Only strings following ? or : are class names — a string before them is
    // the comparison operand (theme === 'dark'), not a selector.
    for (const match of text.matchAll(/className=\{`[^`]*`\}/g)) {
      for (const [, quoted] of match[0].matchAll(/[?:]\s*'([\w\s-]*)'/g)) {
        used.push(...quoted.split(/\s+/).filter(Boolean));
      }
    }

    const missing = [...new Set(used)].filter(
      (c) => !definedClasses.has(c) && !EXTERNAL.has(c)
    );

    expect(missing).toEqual([]);
  });
});

describe('Card Catalog system invariants', () => {
  it('defines the full radius scale, including the previously missing --radius-xs', () => {
    for (const token of ['--radius-xs', '--radius-sm', '--radius-md', '--radius-lg']) {
      expect(definedTokens.has(token)).toBe(true);
    }
  });

  it('defines the spin animation the loading indicators rely on', () => {
    expect(css).toMatch(/@keyframes\s+spin\b/);
    expect(css).toMatch(/\.spin\s*\{[^}]*animation:\s*spin/);
  });

  it('pairs every animation class with a declared keyframe', () => {
    const used = [...css.matchAll(/animation:\s*([\w-]+)/g)].map((m) => m[1]);
    const declared = new Set([...css.matchAll(/@keyframes\s+([\w-]+)/g)].map((m) => m[1]));

    for (const name of new Set(used)) {
      expect(declared.has(name)).toBe(true);
    }
  });

  it('bundles its typography locally so a self-hosted instance needs no network', () => {
    // The design's three faces are pulled from @fontsource and bundled by Vite
    // as local woff2. Nothing may reach out to a font CDN at runtime — that
    // would make an offline instance render in a fallback face, or hang.
    const entry = fs.readFileSync(path.join(srcDir, 'main.jsx'), 'utf8');
    const html = fs.readFileSync(path.join(srcDir, '..', 'index.html'), 'utf8');

    for (const text of [css, entry, html]) {
      expect(text).not.toMatch(/fonts\.googleapis\.com/);
      expect(text).not.toMatch(/fonts\.gstatic\.com/);
    }
    expect(css).not.toMatch(/@import\s+url\(/);

    for (const family of ['spectral', 'archivo', 'courier-prime']) {
      expect(entry).toMatch(new RegExp(`@fontsource/${family}/`));
    }
  });

  it('keeps a system-face fallback behind every bundled family', () => {
    // A woff2 that has not painted yet must land on a real book face, not on
    // the browser's default — that reads as unfinished rather than archival.
    expect(css).toMatch(/--font-display:\s*'Spectral'[^;]*serif/);
    expect(css).toMatch(/--font-body:\s*'Archivo'[^;]*sans-serif/);
    expect(css).toMatch(/--font-stamp:\s*'Courier Prime'[^;]*monospace/);
  });

  it('drops the glassmorphism blur the redesign replaced', () => {
    expect(cssDeclarations).not.toMatch(/backdrop-filter/i);
  });

  it('honours prefers-reduced-motion', () => {
    expect(css).toMatch(/@media\s*\(prefers-reduced-motion:\s*reduce\)/);
  });

  it('keeps the responsive shell in the stylesheet rather than an injected style tag', () => {
    expect(css).toMatch(/@media\s*\(max-width:\s*860px\)/);
    for (const source of sources) {
      expect(source.text).not.toMatch(/document\.head\.appendChild/);
    }
  });
});
